CREATE TABLE dbo.Media
(
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Media_Id DEFAULT NEWSEQUENTIALID(),
	Name NVARCHAR(255) NOT NULL,
	ContentType NVARCHAR(255) NOT NULL,
	Content VARBINARY(MAX) NOT NULL,
	UserId INT NULL CONSTRAINT FK_Media_UserId FOREIGN KEY REFERENCES dbo.Users(Id),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Media_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT PK_Media PRIMARY KEY (Id)
)
