CREATE TABLE dbo.Orders
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Orders PRIMARY KEY,
	SessionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Orders_SessionId DEFAULT NEWID(),
	UserId INT NOT NULL CONSTRAINT FK_Orders_UserId FOREIGN KEY REFERENCES dbo.Users(Id),
	Amount DECIMAL(9,2) NOT NULL,
	Currency CHAR(3) NOT NULL,
	PaymentMethod VARCHAR(255) NOT NULL,
	PaymentToken NVARCHAR(255) NULL,
	Status TINYINT NOT NULL CONSTRAINT DF_Orders_Status DEFAULT 0,
	ExpireDate DATETIME2(0) NOT NULL,
	IsExpired AS CONVERT(BIT, CASE WHEN Status = 0 AND ExpireDate < SYSDATETIME() THEN 1 ELSE 0 END),
	UpdateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Orders_UpdateDate DEFAULT SYSDATETIME(),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Orders_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT UK_Orders_SessionId UNIQUE (SessionId),
	INDEX IDX_UserId (UserId),
	INDEX IDX_CreateDate (CreateDate)
)
