CREATE TABLE dbo.Orders
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Orders PRIMARY KEY,
	UserId INT NOT NULL CONSTRAINT FK_Orders_UserId FOREIGN KEY REFERENCES dbo.Users(Id),
	Amount DECIMAL(9,2) NOT NULL,
	Currency CHAR(3) NOT NULL,
	PaymentMethod VARCHAR(255) NOT NULL,
	PaymentToken NVARCHAR(255) NULL,
	Status TINYINT NOT NULL,
	ExpireDate DATETIME2(0) NOT NULL,
	IsExpired AS CAST(IIF (Status = 0 AND ExpireDate < SYSDATETIME(), 1, 0) AS BIT),
	UpdateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Orders_UpdateDate DEFAULT SYSDATETIME(),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Orders_CreateDate DEFAULT SYSDATETIME()
)
