CREATE TABLE dbo.ResetPasswordRequests
(
	Id INT NOT NULL IDENTITY (1, 1) CONSTRAINT PK_ResetPasswordRequests PRIMARY KEY,
	UserId INT NOT NULL CONSTRAINT FK_ResetPasswordRequests_UserId FOREIGN KEY REFERENCES dbo.Users(Id),
	SecretKey UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ResetPasswordRequests_SecretKey DEFAULT (NEWID()),
	ExpireDate DATETIME2(0) NOT NULL,
	IsExpired AS CONVERT(BIT,CASE WHEN [ExpireDate] > SYSDATETIME() THEN 0 ELSE 1 END),
	ResetDate DATETIME2(0) NULL,
	IsReset AS CONVERT(BIT,CASE WHEN ResetDate IS NULL THEN 0 ELSE 1 END),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_ResetPasswordRequests_CreateDate DEFAULT (SYSDATETIME()),
	CONSTRAINT UK_ResetPasswordRequests UNIQUE (SecretKey)
);