CREATE TABLE dbo.ShowGallery
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ShowGallery PRIMARY KEY,
	ShowId INT NOT NULL CONSTRAINT FK_ShowGallery_ShowId FOREIGN KEY REFERENCES dbo.Shows(Id),
	MediaId UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_ShowGallery_MediaId FOREIGN KEY REFERENCES dbo.Media(Id),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_ShowGallery_CreateDate DEFAULT SYSDATETIME()
)
