CREATE TABLE dbo.Shows
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Shows PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(4000) NULL,
	StartDateTime DATETIME2(0) NOT NULL,
	EndDateTime DATETIME2(0) NOT NULL CONSTRAINT CK_Shows_EndDateTime CHECK(EndDateTime >= StartDateTime),
	ThumbnailMediaId UNIQUEIDENTIFIER NULL CONSTRAINT FK_Shows_ThumbnailMediaId FOREIGN KEY REFERENCES dbo.Media(Id),
	AuditoriumId INT NOT NULL CONSTRAINT FK_Shows_AuditoriumId FOREIGN KEY REFERENCES dbo.Auditoriums(Id),
	SellStartDateTime DATETIME2(0) NOT NULL CONSTRAINT DF_Shows_SellStartDateTime DEFAULT SYSDATETIME(),
	IsEnabled BIT NOT NULL CONSTRAINT DF_Shows_IsEnabled DEFAULT 0,
	UpdateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Shows_UpdateDate DEFAULT SYSDATETIME(),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Shows_CreateDate DEFAULT SYSDATETIME()
)
