-- technical view that returns all int values between 1 and 65536
CREATE VIEW dbo.Tally 
AS 
WITH CTE1(N) AS (SELECT N FROM (VALUES(1),(1))a(N)), -- 2
CTE2(N) AS (SELECT 1 FROM CTE1 x CROSS JOIN CTE1 y), -- 4
CTE3(N) AS (SELECT 1 FROM CTE2 x CROSS JOIN CTE2 y), -- 16
CTE4(N) AS (SELECT 1 FROM CTE3 x CROSS JOIN CTE3 y), -- 256
CTETally(N) AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) 
				FROM CTE4 x 
				CROSS JOIN CTE4 y) -- 65536
SELECT * FROM CTETally;